export const ROUTER_PATH = {
  HOME: "/",
  FORM: {
    ROOT: "/form/",
    ORGANIZATION: "/form/organization",
    PERSON: "/form/person",
    INCUBATION: "/form/incubation",
    GUEST: "/form/guest/",
  },
  INCUBATION: "/incubation",
  CALENDAR: "/calendar",
  HACKATHON: "/hackathon",
  NEWS: {
    ROOT: "/news",
    DETAIL: "/news/detail/",
    SEARCH: "/news/search",
    TYPE: "/news/type/",
  },
  SQUARE: "/square",
  OSCAR: "/oscar",
  OSCAR_CEREMONY: "/oscar-ceremony",
  PROJECT: "/project/",
  VOTING: "/voting",
  JOINT_FUND: "/joint-fund",
};
