export const partersData = {
    "list": [
        {
            "approve": 0,
            "id": "3",
            "name": "Bybit",
            "sort": 2,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/diamond/Bybit.png",
            "link": "https://www.bybit.com/",
            "partnersType": 0,
            "style": "{\"height\":\"46px\"}",
            "mobileStyle": "{\"height\":\"30px\"}",
            "createDate": "2023-01-17T06:40:21.384Z",
            "updateDate": "2023-01-17T06:40:21.384Z"
        },
        {
            "approve": 0,
            "id": "104",
            "name": "MANTLE",
            "sort": 0,
            "type": 0,
            "logo": "https://a.moledao.io/assets/partners/mantle.svg",
            "link": "https://www.mantle.xyz/zh",
            "partnersType": 0,
            "style": "{\n  \"height\": \"100px\"\n, \"transform\": \"scale(1.3)\"\n, \"marginRight\": \"10px\"\n}",
            "mobileStyle": "",
            "createDate": "2023-11-08T14:33:10.047Z",
            "updateDate": "2023-11-08T14:33:10.047Z"
        },
        {
            "approve": 0,
            "id": "101",
            "name": "Huawei Cloud",
            "sort": 0,
            "type": 0,
            "logo": "https://a.moledao.io/assets/partners/5562c467380141c083fe3a863f8217fc.jpeg",
            "link": "https://www.huaweicloud.com/intl/en-us/about/index.html",
            "partnersType": 2,
            "style": "{\n  \"height\": \"50px\"\n,\"transform\": \"scale(1.1)\"\n}",
            "mobileStyle": "",
            "createDate": "2023-11-08T14:28:43.945Z",
            "updateDate": "2023-11-08T14:28:43.945Z"
        },
        {
            "approve": 0,
            "id": "100",
            "name": "Scantist",
            "sort": 0,
            "type": 0,
            "logo": "https://a.moledao.io/assets/partners/3274aaece259405d869c310d2039d33c.jpeg",
            "link": "https://scantist.com/",
            "partnersType": 3,
            "style": "",
            "mobileStyle": "",
            "createDate": "2023-11-08T14:25:54.110Z",
            "updateDate": "2023-11-08T14:25:54.110Z"
        },
        {
            "approve": 0,
            "id": "99",
            "name": "LBank Labs",
            "sort": 0,
            "type": 0,
            "logo": "https://pbs.twimg.com/profile_images/1629485685081096194/KKA7E7-u_400x400.jpg",
            "link": "https://www.lbanklabs.com/",
            "partnersType": 3,
            "style": "{\n  \"height\": \"50px\"\n}",
            "mobileStyle": "",
            "createDate": "2023-11-08T14:23:42.400Z",
            "updateDate": "2023-11-08T14:23:42.400Z"
        },
        {
            "approve": 0,
            "id": "98",
            "name": "Hamster",
            "sort": 0,
            "type": 0,
            "logo": "https://pbs.twimg.com/profile_images/1607257837033644033/aB4i6D0M_400x400.jpg",
            "link": "https://hamsternet.io/",
            "partnersType": 3,
            "style": "{\n  \"height\": \"50px\"\n}",
            "mobileStyle": "",
            "createDate": "2023-11-08T14:19:49.117Z",
            "updateDate": "2023-11-08T14:19:49.117Z"
        },
        {
            "approve": 0,
            "id": "97",
            "name": "Amazon Web Services",
            "sort": 0,
            "type": 0,
            "logo": "https://pbs.twimg.com/profile_images/1641476962362302464/K8lb6OtN_400x400.jpg",
            "link": "https://aws.amazon.com/cn/",
            "partnersType": 3,
            "style": "{\n  \"height\": \"50px\"\n}",
            "mobileStyle": "",
            "createDate": "2023-11-08T14:17:08.516Z",
            "updateDate": "2023-11-08T14:17:08.516Z"
        },
        {
            "approve": 0,
            "id": "96",
            "name": "PlatON",
            "sort": 0,
            "type": 0,
            "logo": "https://pbs.twimg.com/profile_images/1615743526909755392/ukLpnnwl_400x400.jpg",
            "link": "https://www.platon.network/",
            "partnersType": 3,
            "style": "{\n  \"height\": \"80px\"\n,\"transform\": \"scale(1.2)\"\n}",
            "mobileStyle": "",
            "createDate": "2023-11-08T14:16:12.707Z",
            "updateDate": "2023-11-08T14:16:12.707Z"
        },
        {
            "approve": 0,
            "id": "95",
            "name": "SharkTeam",
            "sort": 0,
            "type": 0,
            "logo": "https://pbs.twimg.com/profile_images/1569598172313563138/J5MVwsQ6_400x400.png",
            "link": "https://www.sharkteam.org/#globalPartners",
            "partnersType": 3,
            "style": "{\n  \"height\": \"50px\"\n}",
            "mobileStyle": "",
            "createDate": "2023-11-08T14:15:10.520Z",
            "updateDate": "2023-11-08T14:15:10.520Z"
        },
        {
            "approve": 0,
            "id": "94",
            "name": "bubble ai",
            "sort": 0,
            "type": 0,
            "logo": "https://a.moledao.io/assets/partners/47b4f3627a91435baa28a9808ca7344e.jpeg",
            "link": "https://twitter.com/Bubbleai_xyz",
            "partnersType": 3,
            "style": "{\n  \"height\": \"50px\"\n}",
            "mobileStyle": "",
            "createDate": "2023-11-08T14:08:13.685Z",
            "updateDate": "2023-11-08T14:08:13.685Z"
        },
        {
            "approve": 0,
            "id": "93",
            "name": "BlockPi",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/partners/25c2c50bf2844f9ca8d579ab7df5e7b7.png",
            "link": "https://blockpi.io/",
            "partnersType": 5,
            "style": "{\n  \"width\": \"150px\"\n  ,\"transform\": \"scale(1.3)\"\n}",
            "mobileStyle": "{\n  \"height\": \"30px\"\n  ,\"width\": \"30px\"\n  ,\"transform\": \"scale(1)\"\n}",
            "createDate": "2023-07-06T07:56:57.088Z",
            "updateDate": "2023-07-06T07:57:12.000Z"
        },
        {
            "approve": 0,
            "id": "92",
            "name": "KNN3",
            "sort": 0,
            "type": 1,
            "logo": "https://pbs.twimg.com/profile_images/1608684214056288259/4CHmerAx_400x400.jpg",
            "link": "https://www.knn3.xyz/",
            "partnersType": 3,
            "style": "{\n  \"height\": \"50px\"\n  ,\"width\": \"50px\"\n  ,\"transform\": \"scale(1)\"\n}",
            "mobileStyle": "{\n  \"height\": \"30px\"\n  ,\"width\": \"30px\"\n  ,\"transform\": \"scale(1)\"\n}",
            "createDate": "2023-07-06T07:49:17.316Z",
            "updateDate": "2023-07-06T07:49:24.000Z"
        },
        {
            "approve": 0,
            "id": "91",
            "name": "Blockchain Center",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/partners/ea5771f254ad4041b81b5470f0969263.jpeg",
            "link": "https://twitter.com/cofblockchain",
            "partnersType": 5,
            "style": "{\n  \"height\": \"50px\"\n  ,\"width\": \"50px\"\n  ,\"transform\": \"scale(1)\"\n}",
            "mobileStyle": "{\n  \"height\": \"30px\"\n  ,\"width\": \"30px\"\n  ,\"transform\": \"scale(1)\"\n}",
            "createDate": "2023-07-06T07:45:20.675Z",
            "updateDate": "2023-07-06T07:57:10.000Z"
        },
        {
            "approve": 0,
            "id": "90",
            "name": "VentureFlow",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/partners/2e694b2a2b7b44419eda450022589e75.png",
            "link": "https://www.ventureflow.xyz/",
            "partnersType": 2,
            "style": "{\n  \"height\": \"30px\"\n}",
            "mobileStyle": "{\n  \"height\": \"30px\"\n  ,\"width\": \"30px\"\n  ,\"transform\": \"scale(1)\"\n}",
            "createDate": "2023-07-06T07:31:34.844Z",
            "updateDate": "2023-07-06T07:31:37.000Z"
        },
        {
            "approve": 0,
            "id": "88",
            "name": "TinTinLand",
            "sort": 0,
            "type": 1,
            "logo": "https://pbs.twimg.com/profile_images/1468086243640578049/3CQzdA-__400x400.jpg",
            "link": "https://twitter.com/Tintinland2021",
            "partnersType": 5,
            "style": "{\n  \"height\": \"50px\"\n  ,\"width\": \"50px\"\n  ,\"transform\": \"scale(1)\"\n}",
            "mobileStyle": "{\n  \"height\": \"30px\"\n  ,\"width\": \"30px\"\n  ,\"transform\": \"scale(1)\"\n}",
            "createDate": "2023-07-06T07:27:58.239Z",
            "updateDate": "2023-07-06T07:28:00.000Z"
        },
        {
            "approve": 0,
            "id": "87",
            "name": "Bewater",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/partners/82353ac2775645b68f0b64ed86648f52.png",
            "link": "https://bewater.xyz/",
            "partnersType": 5,
            "style": "{\n  \"height\": \"50px\"\n  ,\"width\": \"50px\"\n  ,\"transform\": \"scale(1)\"\n}",
            "mobileStyle": "{\n  \"height\": \"30px\"\n  ,\"width\": \"30px\"\n  ,\"transform\": \"scale(1)\"\n}",
            "createDate": "2023-07-06T07:26:38.781Z",
            "updateDate": "2023-07-06T07:26:41.000Z"
        },
        {
            "approve": 0,
            "id": "86",
            "name": "Odaily",
            "sort": 0,
            "type": 1,
            "logo": "https://pbs.twimg.com/profile_images/1495985029305884674/2YQby7Cz_400x400.png",
            "link": "https://www.odaily.news/",
            "partnersType": 4,
            "style": "{\n  \"width\": \"50px\"\n  ,\"transform\": \"scale(1)\"\n}",
            "mobileStyle": "{\n  \"height\": \"50px\"\n  ,\"transform\": \"scale(1)\"\n}",
            "createDate": "2023-07-06T07:23:46.061Z",
            "updateDate": "2023-07-06T07:23:48.000Z"
        },
        {
            "approve": 0,
            "id": "85",
            "name": "Cointime",
            "sort": 0,
            "type": 1,
            "logo": "https://pbs.twimg.com/profile_images/1677957552829792257/d48jKbXG_400x400.jpg",
            "link": "https://www.cointime.com/",
            "partnersType": 4,
            "style": "{\n  \"width\": \"50px\"\n  ,\"transform\": \"scale(1)\"\n}",
            "mobileStyle": "{\n  \"width\": \"50px\"\n  ,\"transform\": \"scale(1)\"\n}",
            "createDate": "2023-07-06T07:21:55.804Z",
            "updateDate": "2023-07-06T07:21:59.000Z"
        },
        {
            "approve": 0,
            "id": "83",
            "name": "Coinbay",
            "sort": 0,
            "type": 1,
            "logo": "https://coinbay.io/_nuxt/img/logo.c5beb9b.svg",
            "link": "https://coinbay.io/vi/home/",
            "partnersType": 5,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-02-24T04:10:21.036Z",
            "updateDate": "2023-02-24T04:10:21.036Z"
        },
        {
            "approve": 0,
            "id": "82",
            "name": "ICcafe",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/iccafe.jpeg",
            "link": "http://www.iccafe.sg/",
            "partnersType": 5,
            "style": "{\n  \"height\": \"44px\"\n}",
            "mobileStyle": "{\"height\": \"30px\"}",
            "createDate": "2023-02-02T05:59:38.931Z",
            "updateDate": "2023-02-02T05:59:38.931Z"
        },
        {
            "approve": 0,
            "id": "81",
            "name": "AlibabaCloud",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/alibaba.png",
            "link": "https://hk.alibabacloud.com/",
            "partnersType": 5,
            "style": "{\n  \"height\": \"44px\"\n  ,\"transform\": \"scale(2)\"\n}",
            "mobileStyle": "",
            "createDate": "2023-02-02T05:38:29.882Z",
            "updateDate": "2023-02-02T05:38:29.882Z"
        },
        {
            "approve": 0,
            "id": "80",
            "name": "theblockbeats",
            "sort": 0,
            "type": 1,
            "logo": "https://pbs.twimg.com/profile_images/1588454205739929600/i4el9P5L_400x400.jpg",
            "link": "https://www.theblockbeats.info/",
            "partnersType": 4,
            "style": "{\"height\": \"44px\"}",
            "mobileStyle": "{\"height\":\"30px\"}",
            "createDate": "2023-01-30T14:56:35.869Z",
            "updateDate": "2023-07-04T10:38:22.000Z"
        },
        {
            "approve": 0,
            "id": "79",
            "name": "metatrust",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/metatrust.jpeg",
            "link": "https://metatrust.io/",
            "partnersType": 5,
            "style": "{\"height\": \"44px\"}",
            "mobileStyle": "{\"height\":\"30px\"}",
            "createDate": "2023-01-30T14:51:46.223Z",
            "updateDate": "2023-01-30T14:51:46.223Z"
        },
        {
            "approve": 0,
            "id": "74",
            "name": "backwave2022",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/backwave.jpeg",
            "link": "https://twitter.com/backwave2022",
            "partnersType": 5,
            "style": "{\"height\":\"100%\",\"scale\":\"1.5\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.560Z",
            "updateDate": "2023-01-17T06:40:21.560Z"
        },
        {
            "approve": 0,
            "id": "73",
            "name": "LXDAO",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/lxdao.jpg",
            "link": "https://lxdao.io/",
            "partnersType": 5,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.559Z",
            "updateDate": "2023-01-17T06:40:21.559Z"
        },
        {
            "approve": 0,
            "id": "72",
            "name": "ABGA",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/abga.jpeg",
            "link": "https://www.abga.asia/",
            "partnersType": 5,
            "style": "{\"height\":\"22px\",\"width\":\"80%\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.558Z",
            "updateDate": "2023-01-17T06:40:21.558Z"
        },
        {
            "approve": 0,
            "id": "71",
            "name": "ORC",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/orc.jpg",
            "link": "https://twitter.com/_ORCTrade",
            "partnersType": 5,
            "style": "{\"height\":\"46px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.556Z",
            "updateDate": "2023-01-17T06:40:21.556Z"
        },
        {
            "approve": 0,
            "id": "70",
            "name": "ILLA Cloud",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/ILLA.png",
            "link": "https://www.illacloud.com",
            "partnersType": 5,
            "style": "{\"height\":\"26px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.552Z",
            "updateDate": "2023-01-17T06:40:21.552Z"
        },
        {
            "approve": 0,
            "id": "69",
            "name": "Olandbox",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/olandbox.jpg",
            "link": "https://oland.info/olandbox.v",
            "partnersType": 5,
            "style": "{\"height\":\"46px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.551Z",
            "updateDate": "2023-01-17T06:40:21.551Z"
        },
        {
            "approve": 0,
            "id": "68",
            "name": "StartupX",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/startupx.png",
            "link": "https://thestartupx.com",
            "partnersType": 5,
            "style": "{\"height\":\"30px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.549Z",
            "updateDate": "2023-01-17T06:40:21.549Z"
        },
        {
            "approve": 0,
            "id": "67",
            "name": "web3job",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/web3job.png",
            "link": "https://twitter.com/web3job1",
            "partnersType": 5,
            "style": "{\"height\":\"50px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.547Z",
            "updateDate": "2023-01-17T06:40:21.547Z"
        },
        {
            "approve": 0,
            "id": "66",
            "name": "APAC",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/apac.jpg",
            "link": "https://www.apacdao.net",
            "partnersType": 5,
            "style": "{\"height\":\"50px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.546Z",
            "updateDate": "2023-01-17T06:40:21.546Z"
        },
        {
            "approve": 0,
            "id": "65",
            "name": "SBIP",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/SingaporeBlockchainInnovationProgramme.png",
            "link": "https://sbip.sg/#ourMission",
            "partnersType": 5,
            "style": "{\"height\":\"40px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.545Z",
            "updateDate": "2023-01-17T06:40:21.545Z"
        },
        {
            "approve": 0,
            "id": "64",
            "name": "Beosin Blockchain Security",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/BEOSIN1.png",
            "link": "https://beosin.com/#/index/home",
            "partnersType": 5,
            "style": "{\"height\":\"35px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.543Z",
            "updateDate": "2023-01-17T06:40:21.543Z"
        },
        {
            "approve": 0,
            "id": "63",
            "name": "Winkrypto",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/winkrypto-dark.png",
            "link": "https://winkrypto.com/",
            "partnersType": 5,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.540Z",
            "updateDate": "2023-01-17T06:40:21.540Z"
        },
        {
            "approve": 0,
            "id": "62",
            "name": "Webx",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/webex.png",
            "link": "https://www.webex.com/",
            "partnersType": 5,
            "style": "{\"height\":\"30px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.538Z",
            "updateDate": "2023-01-17T06:40:21.538Z"
        },
        {
            "approve": 0,
            "id": "61",
            "name": "We3",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/WE3-LOGO-FINAL.png",
            "link": "https://www.hello-we3.com/",
            "partnersType": 5,
            "style": "{\"height\":\"40px\"}",
            "mobileStyle": "{\"height\":\"24px\"}",
            "createDate": "2023-01-17T06:40:21.536Z",
            "updateDate": "2023-01-17T06:40:21.536Z"
        },
        {
            "approve": 0,
            "id": "60",
            "name": "University-Of-Oulu",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/UniversityofOulu.png",
            "link": "https://www.oulu.fi/en",
            "partnersType": 5,
            "style": "{\"height\":\"44px\"}",
            "mobileStyle": "{\"height\":\"30px\"}",
            "createDate": "2023-01-17T06:40:21.535Z",
            "updateDate": "2023-01-17T06:40:21.535Z"
        },
        {
            "approve": 0,
            "id": "59",
            "name": "Reddio",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/Reddio.png",
            "link": "https://www.reddio.com/",
            "partnersType": 5,
            "style": "{\"height\":\"24px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.534Z",
            "updateDate": "2023-01-17T06:40:21.534Z"
        },
        {
            "approve": 0,
            "id": "58",
            "name": "Project Galaxy",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/ProjectGalaxy.png",
            "link": "https://galaxy.eco/",
            "partnersType": 5,
            "style": "{\n  \"height\": \"16px\"\n}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.532Z",
            "updateDate": "2023-01-17T06:40:21.532Z"
        },
        {
            "approve": 0,
            "id": "57",
            "name": "Outlier Dao",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/Outliers.png",
            "link": "https://outliers.fund",
            "partnersType": 5,
            "style": "{\"height\":\"36px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.531Z",
            "updateDate": "2023-01-17T06:40:21.531Z"
        },
        {
            "approve": 0,
            "id": "56",
            "name": "NUS Fintech Lab",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/NUS.png",
            "link": "https://fintechlab.nus.edu.sg/zh/home-chinese/",
            "partnersType": 5,
            "style": "{\"height\":\"30px\"}",
            "mobileStyle": "{\"height\":\"20px\"}",
            "createDate": "2023-01-17T06:40:21.529Z",
            "updateDate": "2023-01-17T06:40:21.529Z"
        },
        {
            "approve": 0,
            "id": "55",
            "name": "Metisign",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/Metisign.png",
            "link": "https://www.metisign.com/",
            "partnersType": 5,
            "style": "{\"height\":\"30px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.522Z",
            "updateDate": "2023-01-17T06:40:21.522Z"
        },
        {
            "approve": 0,
            "id": "54",
            "name": "Metaschool",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/metaschool.png",
            "link": "https://metaschool.so/",
            "partnersType": 5,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.515Z",
            "updateDate": "2023-01-17T06:40:21.515Z"
        },
        {
            "approve": 0,
            "id": "53",
            "name": "Longhash Ventures",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/LonghashVentures.png",
            "link": "https://longhash.vc/",
            "partnersType": 5,
            "style": "{\"height\":\"26px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.513Z",
            "updateDate": "2023-01-17T06:40:21.513Z"
        },
        {
            "approve": 0,
            "id": "52",
            "name": "degame",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/Degame.png",
            "link": "https://www.degame.com/zh/home",
            "partnersType": 3,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.512Z",
            "updateDate": "2023-01-17T06:40:21.512Z"
        },
        {
            "approve": 0,
            "id": "51",
            "name": "Lambdasoc",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/LambdaCommunity.png",
            "link": "https://twitter.com/Lambda_Web3",
            "partnersType": 5,
            "style": "{\"width\":\"44px\",\"height\":\"44px\"}",
            "mobileStyle": "{\"height\":\"30px\"}",
            "createDate": "2023-01-17T06:40:21.511Z",
            "updateDate": "2023-01-17T06:40:21.511Z"
        },
        {
            "approve": 0,
            "id": "50",
            "name": "Hackerhut",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/HackerspaceSG.png",
            "link": "https://hackerspace.sg/about/",
            "partnersType": 5,
            "style": "{\"height\":\"40px\"}",
            "mobileStyle": "{\"height\":\"20px\"}",
            "createDate": "2023-01-17T06:40:21.507Z",
            "updateDate": "2023-01-17T06:40:21.507Z"
        },
        {
            "approve": 0,
            "id": "49",
            "name": "Grit",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/Grit.png",
            "link": "https://gritsearch.com/",
            "partnersType": 5,
            "style": "{\"height\":\"40px\"}",
            "mobileStyle": "{\"height\":\"20px\"}",
            "createDate": "2023-01-17T06:40:21.504Z",
            "updateDate": "2023-01-17T06:40:21.504Z"
        },
        {
            "approve": 0,
            "id": "48",
            "name": "Force Community",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/ForceCommunity.png",
            "link": "https://forcecommunity.io/",
            "partnersType": 5,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.501Z",
            "updateDate": "2023-01-17T06:40:21.501Z"
        },
        {
            "approve": 0,
            "id": "47",
            "name": "Ethsign",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/Ethsign.png",
            "link": "https://www.ethsign.xyz/",
            "partnersType": 5,
            "style": "{\"height\":\"34px\"}",
            "mobileStyle": "{\"height\":\"22px\"}",
            "createDate": "2023-01-17T06:40:21.498Z",
            "updateDate": "2023-01-17T06:40:21.498Z"
        },
        {
            "approve": 0,
            "id": "46",
            "name": "Eth Shanghai",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/ethshanghai1.png",
            "link": "https://www.ethshanghai.org",
            "partnersType": 5,
            "style": "{\"height\":\"40px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.495Z",
            "updateDate": "2023-01-17T06:40:21.495Z"
        },
        {
            "approve": 0,
            "id": "45",
            "name": "CrossSpace",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/crossspace.png",
            "link": "https://www.crossspace.io",
            "partnersType": 5,
            "style": "{\"height\":\"30px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.493Z",
            "updateDate": "2023-01-17T06:40:21.493Z"
        },
        {
            "approve": 0,
            "id": "44",
            "name": "Astrox Me",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/AstroxMe.png",
            "link": "https://astrox.me/",
            "partnersType": 5,
            "style": "{\"height\":\"26px\"}",
            "mobileStyle": "{\"height\":\"12px\"}",
            "createDate": "2023-01-17T06:40:21.489Z",
            "updateDate": "2023-01-17T06:40:21.489Z"
        },
        {
            "approve": 0,
            "id": "43",
            "name": "Thubadao",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/thubadao.png",
            "link": "https://www.thubadao.xyz/",
            "partnersType": 5,
            "style": "{\"height\":\"30px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.486Z",
            "updateDate": "2023-01-17T06:40:21.486Z"
        },
        {
            "approve": 0,
            "id": "42",
            "name": "PermaDAO",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/Permadao.png",
            "link": "https://permadao.notion.site/",
            "partnersType": 5,
            "style": "{\"height\":\"42px\"}",
            "mobileStyle": "{\"height\":\"30px\"}",
            "createDate": "2023-01-17T06:40:21.483Z",
            "updateDate": "2023-01-17T06:40:21.483Z"
        },
        {
            "approve": 0,
            "id": "41",
            "name": "My MetaData",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/MyMetaData.png",
            "link": "https://www.mymetadata.io/",
            "partnersType": 5,
            "style": "{\"height\":\"24px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.481Z",
            "updateDate": "2023-01-17T06:40:21.481Z"
        },
        {
            "approve": 0,
            "id": "40",
            "name": "Ceres DAO",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/CeresDAO.png",
            "link": "https://ceresdao.finance/",
            "partnersType": 5,
            "style": "{\"height\":\"40px\"}",
            "mobileStyle": "{\"height\":\"30px\"}",
            "createDate": "2023-01-17T06:40:21.478Z",
            "updateDate": "2023-01-17T06:40:21.478Z"
        },
        {
            "approve": 0,
            "id": "39",
            "name": "TYPE V DAO",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/TYPEVDAO.png",
            "link": "https://www.typevdao.io/#",
            "partnersType": 5,
            "style": "{\"height\":\"30px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.475Z",
            "updateDate": "2023-01-17T06:40:21.475Z"
        },
        {
            "approve": 0,
            "id": "38",
            "name": "CodingGirls",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/CodingGirls.png",
            "link": "https://codinggirls.sg/",
            "partnersType": 5,
            "style": "{\"height\":\"28px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.472Z",
            "updateDate": "2023-01-17T06:40:21.472Z"
        },
        {
            "approve": 0,
            "id": "37",
            "name": "Numen Cyber",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/NumenLogo.png",
            "link": "https://numencyber.com/",
            "partnersType": 5,
            "style": "{\"height\":\"28px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.467Z",
            "updateDate": "2023-01-17T06:40:21.467Z"
        },
        {
            "approve": 0,
            "id": "36",
            "name": "zcloak",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/zCloak.png",
            "link": "https://zcloak.network/#/",
            "partnersType": 5,
            "style": "{\"width\":\"80px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.464Z",
            "updateDate": "2023-01-17T06:40:21.464Z"
        },
        {
            "approve": 0,
            "id": "35",
            "name": "p12",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/ProjectTwelve.png",
            "link": "https://p12.network/",
            "partnersType": 1,
            "style": "{\"height\":\"40px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.460Z",
            "updateDate": "2023-01-17T06:40:21.460Z"
        },
        {
            "approve": 0,
            "id": "34",
            "name": "Mometa",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/MoMeTa.png",
            "link": "https://mometa.io/",
            "partnersType": 5,
            "style": "{\"height\":\"30px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.454Z",
            "updateDate": "2023-01-17T06:40:21.454Z"
        },
        {
            "approve": 0,
            "id": "33",
            "name": "Muadao",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/MUADAO.png",
            "link": "https://twitter.com/MUA_MUaDAO",
            "partnersType": 5,
            "style": "{\"height\":\"36px\"}",
            "mobileStyle": "{\"height\":\"30px\"}",
            "createDate": "2023-01-17T06:40:21.451Z",
            "updateDate": "2023-01-17T06:40:21.451Z"
        },
        {
            "approve": 0,
            "id": "32",
            "name": "BuidlerDAO",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/BuilderDAO.png",
            "link": "https://buidlerdao.xyz/",
            "partnersType": 5,
            "style": "{\"height\":\"56px\"}",
            "mobileStyle": "{\"height\":\"34px\"}",
            "createDate": "2023-01-17T06:40:21.449Z",
            "updateDate": "2023-01-17T06:40:21.449Z"
        },
        {
            "approve": 0,
            "id": "31",
            "name": "avademy",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/academy.png",
            "link": "https://twitter.com/Blockchain_AC",
            "partnersType": 5,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.448Z",
            "updateDate": "2023-01-17T06:40:21.448Z"
        },
        {
            "approve": 0,
            "id": "30",
            "name": "ContentFi",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/community/ContentFi.png",
            "link": "https://contentfi.net",
            "partnersType": 5,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.446Z",
            "updateDate": "2023-01-17T06:40:21.446Z"
        },
        {
            "approve": 0,
            "id": "29",
            "name": "Blocklike",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/media/blocklike.png",
            "link": "https://twitter.com/blocklikecom",
            "partnersType": 4,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.442Z",
            "updateDate": "2023-01-17T06:40:21.442Z"
        },
        {
            "approve": 0,
            "id": "28",
            "name": "TechFlow",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/media/teckflow.jpg",
            "link": "https://m.techflowpost.com/",
            "partnersType": 4,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.439Z",
            "updateDate": "2023-01-17T06:40:21.439Z"
        },
        {
            "approve": 0,
            "id": "27",
            "name": "Mpost",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/media/MetaversePost_logo-02.png",
            "link": "https://mpost.io/",
            "partnersType": 4,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.436Z",
            "updateDate": "2023-01-17T06:40:21.436Z"
        },
        {
            "approve": 0,
            "id": "26",
            "name": "jinse",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/media/jinse.png",
            "link": "https://www.jinse.com/",
            "partnersType": 4,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.435Z",
            "updateDate": "2023-01-17T06:40:21.435Z"
        },
        {
            "approve": 0,
            "id": "25",
            "name": "Marsbit",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/media/Marsbitlogo1.png",
            "link": "https://www.marsbit.co/",
            "partnersType": 4,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.434Z",
            "updateDate": "2023-01-17T06:40:21.434Z"
        },
        {
            "approve": 0,
            "id": "24",
            "name": "ForesightNews",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/media/foresightnews.png",
            "link": "https://foresightnews.pro/article",
            "partnersType": 4,
            "style": "{\"height\":\"32px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.433Z",
            "updateDate": "2023-01-17T06:40:21.433Z"
        },
        {
            "approve": 0,
            "id": "23",
            "name": "Coinlive",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/media/Coinlivelogo2.png",
            "link": "https://www.coinlive.com/",
            "partnersType": 4,
            "style": "{\"height\":\"30px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.430Z",
            "updateDate": "2023-01-17T06:40:21.430Z"
        },
        {
            "approve": 0,
            "id": "22",
            "name": "CointelegraphCN",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/media/ctclogo.jpg",
            "link": "https://cointelegraphcn.com/",
            "partnersType": 4,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.428Z",
            "updateDate": "2023-01-17T06:40:21.428Z"
        },
        {
            "approve": 0,
            "id": "21",
            "name": "blockcast",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/media/BlockcastLogo.png",
            "link": "https://blockcast.cc/",
            "partnersType": 4,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.427Z",
            "updateDate": "2023-01-17T06:40:21.427Z"
        },
        {
            "approve": 0,
            "id": "20",
            "name": "spheron",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/silver/spheron.jpg",
            "link": "https://spheron.network/",
            "partnersType": 3,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.426Z",
            "updateDate": "2023-01-17T06:40:21.426Z"
        },
        {
            "approve": 0,
            "id": "19",
            "name": "numencyber",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/silver/numencyber.png",
            "link": "https://numencyber.com/",
            "partnersType": 3,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.423Z",
            "updateDate": "2023-01-17T06:40:21.423Z"
        },
        {
            "approve": 0,
            "id": "18",
            "name": "slash",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/silver/slash.png",
            "link": "https://slash.sg/",
            "partnersType": 3,
            "style": "{\"height\":\"26px\"}",
            "mobileStyle": "{\"height\":\"22px\"}",
            "createDate": "2023-01-17T06:40:21.420Z",
            "updateDate": "2023-01-17T06:40:21.420Z"
        },
        {
            "approve": 0,
            "id": "17",
            "name": "starrynift",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/silver/StarryNift.png",
            "link": "https://starrynift.art/starryverse",
            "partnersType": 3,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.418Z",
            "updateDate": "2023-01-17T06:40:21.418Z"
        },
        {
            "approve": 0,
            "id": "16",
            "name": "quest3",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/silver/Quest3.png",
            "link": "https://quest3.xyz/",
            "partnersType": 3,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.416Z",
            "updateDate": "2023-01-17T06:40:21.416Z"
        },
        {
            "approve": 0,
            "id": "15",
            "name": "OGBC",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/silver/OGBC.png",
            "link": "https://ogbc.com",
            "partnersType": 3,
            "style": "{\"height\":\"34px\"}",
            "mobileStyle": "{\"height\":\"30px\"}",
            "createDate": "2023-01-17T06:40:21.414Z",
            "updateDate": "2023-01-17T06:40:21.414Z"
        },
        {
            "approve": 0,
            "id": "14",
            "name": "Polkastarter",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/silver/Polkastarter.png",
            "link": "https://polkastarter.com/",
            "partnersType": 3,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.412Z",
            "updateDate": "2023-01-17T06:40:21.412Z"
        },
        {
            "approve": 0,
            "id": "12",
            "name": "YBB",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/gold/YBBLOGO.png",
            "link": "http://www.ybb.io/",
            "partnersType": 2,
            "style": "{\"height\":\"30px\"}",
            "mobileStyle": "{\"height\":\"26px\"}",
            "createDate": "2023-01-17T06:40:21.408Z",
            "updateDate": "2023-01-17T06:40:21.408Z"
        },
        {
            "approve": 0,
            "id": "11",
            "name": "Thirdweb",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/gold/thirdwebLogoPrimary.png",
            "link": "https://thirdweb.com/",
            "partnersType": 2,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.406Z",
            "updateDate": "2023-01-17T06:40:21.406Z"
        },
        {
            "approve": 0,
            "id": "10",
            "name": "NGC Ventures",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/gold/NGCVentureslogo.png",
            "link": "https://ngc.fund/",
            "partnersType": 2,
            "style": "{\"height\":\"30px\"}",
            "mobileStyle": "{\"height\":\"26px\"}",
            "createDate": "2023-01-17T06:40:21.402Z",
            "updateDate": "2023-01-17T06:40:21.402Z"
        },
        {
            "approve": 0,
            "id": "9",
            "name": "Mask Network",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/gold/MaskNetworklogo.png",
            "link": "https://mask.io/",
            "partnersType": 2,
            "style": "{\"height\":\"30px\"}",
            "mobileStyle": "{\"height\":\"30px\"}",
            "createDate": "2023-01-17T06:40:21.400Z",
            "updateDate": "2023-01-17T06:40:21.400Z"
        },
        {
            "approve": 0,
            "id": "8",
            "name": "Buildspace",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/gold/buildspace.png",
            "link": "https://buildspace.so/",
            "partnersType": 2,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.398Z",
            "updateDate": "2023-01-17T06:40:21.398Z"
        },
        {
            "approve": 0,
            "id": "7",
            "name": "Polygon",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/platinum/Polygon.png",
            "link": "https://polygon.technology/",
            "partnersType": 1,
            "style": "{\"height\":\"40px\"}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.396Z",
            "updateDate": "2023-01-17T06:40:21.396Z"
        },
        {
            "approve": 0,
            "id": "6",
            "name": "Atlas Capital",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/platinum/AtlasCapital.png",
            "link": "http://www.atlascap.com.cn/",
            "partnersType": 1,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.395Z",
            "updateDate": "2023-01-17T06:40:21.395Z"
        },
        {
            "approve": 0,
            "id": "5",
            "name": "Alchemy Pay",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/platinum/AlchemyPay.png",
            "link": "https://alchemypay.org/",
            "partnersType": 1,
            "style": "{}",
            "mobileStyle": "{}",
            "createDate": "2023-01-17T06:40:21.392Z",
            "updateDate": "2023-01-17T06:40:21.392Z"
        },
        {
            "approve": 0,
            "id": "4",
            "name": "Mirana",
            "sort": 0,
            "type": 1,
            "logo": "https://a.moledao.io/assets/logos/diamond/Mirana.png",
            "link": "https://www.mirana.xyz/",
            "partnersType": 0,
            "style": "{\"height\":\"28px\"}",
            "mobileStyle": "{\"height\":\"20px\"}",
            "createDate": "2023-01-17T06:40:21.388Z",
            "updateDate": "2023-01-17T06:40:21.388Z"
        }
    ],
    "total": 95
}